project 'TicTacToe.xcodeproj'
platform :ios, '9.3'

target 'TicTacToe' do
    pod 'Workflow', path: '../../../Workflow.podspec', :testspecs => ['Tests']
    pod 'WorkflowUI', path: '../../../WorkflowUI.podspec', :testspecs => ['Tests']
    pod 'BackStackContainer', path: '../BackStackContainer/BackStackContainer.podspec'
end

target 'TicTacToeTests' do
    pod 'WorkflowTesting', path: '../../../WorkflowTesting.podspec', :testspecs => ['Tests']
end
