project 'SampleSwiftUIApp.xcodeproj'
platform :ios, '13'

target 'SampleSwiftUIApp' do
    pod 'Workflow', path: '../../../Workflow.podspec', :testspecs => ['Tests']
    pod 'WorkflowSwiftUI', path: '../../../WorkflowSwiftUI.podspec'
end
