source 'https://github.com/CocoaPods/Specs.git'
project 'Tutorial.xcodeproj'
platform :ios, '11.0'

target 'Tutorial' do
    pod 'Workflow', path: '../../../Workflow.podspec', :testspecs => ['Tests']
    pod 'WorkflowUI', path: '../../../WorkflowUI.podspec', :testspecs => ['Tests']
    pod 'BackStackContainer', path: '../BackStackContainer/BackStackContainer.podspec'

    pod 'TutorialViews', path: 'Frameworks/TutorialViews/TutorialViews.podspec'
    pod 'TutorialBase', path: 'Frameworks/TutorialBase/TutorialBase.podspec', :testspecs => ['Tests']
    pod 'Tutorial1', path: 'Frameworks/Tutorial1Complete/Tutorial1.podspec'
    pod 'Tutorial2', path: 'Frameworks/Tutorial2Complete/Tutorial2.podspec'
    pod 'Tutorial3', path: 'Frameworks/Tutorial3Complete/Tutorial3.podspec'
    pod 'Tutorial4', path: 'Frameworks/Tutorial4Complete/Tutorial4.podspec', :testspecs => ['Tests']
    pod 'Tutorial5', path: 'Frameworks/Tutorial5Complete/Tutorial5.podspec', :testspecs => ['Tests']
end

target 'TutorialTests' do
    pod 'WorkflowTesting', path: '../../../WorkflowTesting.podspec', :testspecs => ['Tests']
end
